%%  group_analysis_4processed_REM
% Author: Saar Lanir-Azaria
% Date: 03/05/2023
%
% This script loads EEG signals from previously processed REM files
% and merges them for grand average frequency analysis.
%
% Each file is assumed to contain segments generated by the "prep_REM_data" preprocessing pipeline.
%
% Required:
% - FieldTrip toolbox
% - Preprocessed data 
% - scalp_regions and layout files for visualization and region selection

%% Initialize
close all;
clc;

%% Define stage and preprocessing flags
to_log = 0;         % Set to 1 for log-transform of power
to_norm = 0;        % Set to 1 for normalization

%% Set user-defined MATLAB base path (adjust as needed)
path2MATLAB = '<YOUR_PATH>/EEG_analysis'; % <-- Set this path
% Add relevant directories to path

%% Load layout and channel information
load(fullfile(path2MATLAB, 'templates', 'lay.mat'))
[all_eeg, eegLR, scalp_chann] = scalp_regions(2);
chan2use = lay.label; % You may adjust this to include a subset like: [all_eeg{1,2}; all_eeg{1,6}]

%% Loop through experimental groups (e.g., control vs. PD)
for group = [1, 2]

    if group == 11
        files_folder = '<YOUR_PATH>/data/post_ICA_data/15042024/CONTROL';
        group_name = 'control';
    else
        files_folder = '<YOUR_PATH>/data/post_ICA_data/15042024/PD';
        group_name = 'PD';
    end

    %% Compute frequency-domain features for the group
    freq = sleep_group_cal(files_folder, sleep_stage);

    %% Save to group-specific variable
    Varname = strcat('freq_', group_name);
    eval([Varname ' = freq;']);
    clear freq;
end